// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectServer'](arg1, arg2, arg3);
}

export function GetMessage() {
  return window['go']['main']['App']['GetMessage']();
}

export function GetUserInfo(arg1) {
  return window['go']['main']['App']['GetUserInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
