// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectServer(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GetMessage():Promise<string>;

export function GetUserInfo(arg1:number):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;
