// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ethernet} from '../models';

export function Auth(arg1:ethernet.TcpRequest,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ConnectServer(arg1:string,arg2:string,arg3:string):Promise<ethernet.TcpRequest>;

export function GetMessage():Promise<string>;

export function GetUserInfo(arg1:number):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function NewChat(arg1:ethernet.TcpRequest,arg2:string):Promise<void>;

export function NewMessage(arg1:ethernet.TcpRequest,arg2:number,arg3:string):Promise<void>;
