// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth(arg1, arg2, arg3) {
  return window['go']['main']['App']['Auth'](arg1, arg2, arg3);
}

export function ConnectServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectServer'](arg1, arg2, arg3);
}

export function GetMessage() {
  return window['go']['main']['App']['GetMessage']();
}

export function GetUserInfo(arg1) {
  return window['go']['main']['App']['GetUserInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NewChat(arg1) {
  return window['go']['main']['App']['NewChat'](arg1);
}

export function NewMessage(arg1, arg2) {
  return window['go']['main']['App']['NewMessage'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function UpdateChat(arg1) {
  return window['go']['main']['App']['UpdateChat'](arg1);
}
