// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {model} from '../models';

export function Auth(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectServer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetMessage():Promise<string>;

export function GetUserInfo(arg1:number):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function NewChat(arg1:string):Promise<void>;

export function NewMessage(arg1:number,arg2:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateChat(arg1:number):Promise<Record<string, model.Chat>>;
